
trigger:
- main

resources:
  # repositories:
  # - repository: self
  containers:
  # - container: docker-dind
  #   image: docker:18-dind
  # - container: docker-builder
    # image: docker:18-git
  - container: terraform
    image: hashicorp/terraform:0.14.2

# variables:
#   tag: '$(Build.BuildId)'

stages:
- stage: Deploy_Test
  displayName: Deploy_Test
  pool:
    vmImage: 'ubuntu-18.04'
    # demands: agent -equals M$-selfhosted
  jobs:
  - job: Deploy_Work
    displayName: Deploy_Work
    container: terraform
    services:
      docker-dind: docker-dind
    steps:
    - script: echo "Hello world"

# exemplo basico
# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
