trigger:
- main

resources:
  repositories:
  - repository: self
  containers:
  - container: docker-builder
    image: docker:18-git
    # image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard


# variables:
#   tag: '$(Build.BuildId)'

stages:
- stage: Deploy_Test
  displayName: Deploy_Test
  pool:
  #   vmImage: 'ubuntu-18.04'
    name: Default
    demands: agent.name -equals AzDevOps-Agent
  jobs:
  - job: Deploy_Work
    displayName: Deploy_Work
    container: docker-builder
    # services:
      # docker-dind: docker-dind
    steps:
    - script: printenv
      target:
        container: docker-builder
    - task: Docker@2
      inputs:
        command: stop
        container: docker-builder

# exemplo basico
# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
