
trigger:
- main

resources:
  repositories:
  - repository: self
  containers:
  - container: docker-builder
    image: microsoft/vsts-agent:ubuntu-16.04-docker-18.06.1-ce-standard


# variables:
#   tag: '$(Build.BuildId)'

stages:
- stage: Deploy_Test
  displayName: Deploy_Test
  pool:
    vmImage: 'ubuntu-18.04'
    # demands: agent -equals M$-selfhosted
  jobs:
  - job: Deploy_Work
    displayName: Deploy_Work
    container: docker-builder
    # services:
      # docker-dind: docker-dind
    steps:
    - script: |
        docker run -ti --rm --entrypoint /bin/sh hashicorp/terraform:0.14.2 -c printenv

# exemplo basico
# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
